### ISSUE TITLE
getComputedStyle doesn't work as expected

### ISSUE THREAD

**Issue by MoOx** [jonathantneal/Polyfills-for-IE8#3]
`getComputedStyle.getPropertyValue()` doesn't work. Why did you leave a empty method ?

**Comment by patocallaghan** [comment]
Hey @MoOx,

I've added a simple polyfill for `getPropertyValue` [here](https://github.com/jonathantneal/Polyfills-for-IE8/pull/4)

**Comment by jonathantneal** [comment]
Merged!

**Comment by jonathantneal** [comment]
FYI, all of these changes are being merged into https://github.com/jonathantneal/polyfill

That is now the motherload of polyfills.
